name: delivery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get: ^4.6.6
  json_annotation: ^4.9.0
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.10

flutter:
  fonts:
    - family: LemonMilk
      fonts:
        - asset: assets/fonts/LEMONMILK-Bold.otf
          weight: 700
        - asset: assets/fonts/LEMONMILK-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/LEMONMILK-Light.otf
          weight: 300
        - asset: assets/fonts/LEMONMILK-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/LEMONMILK-Medium.otf
          weight: 500
        - asset: assets/fonts/LEMONMILK-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/LEMONMILK-Regular.otf
          weight: 400
        - asset: assets/fonts/LEMONMILK-RegularItalic.otf
          weight: 400
          style: italic

  uses-material-design: true

  assets:
    - assets/
